[package]
name = "germinal_rs"
version = "0.1.0"
edition = "2021"
description = "Rust library used by Germinal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
rustler = "0.32.1"

[lib]
crate-type = ["dylib"]
